version: "1.0"

services:
  frontend:
    build: ./frontend/
    ports:
        - "3000:3000"
    volumes: 
      - ./frontend:/app
  backend:
    build: ./backend/
    ports: 
      - "9000:9000"
    volumes: 
      - ./backend:/app

  admin-client: 
    build: ./admin-client/
    ports: 
        - "3001:3000"
    volumes: 
      - ./admin-client:/app
   