version: "3.7"

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./admin-client/
      dockerfile: dev.Dockerfile
    ports:
        - "3000:3000"
    volumes: 
      - ./frontend:/app
    networks:
    - INTIA_APP
    environment:
       CHOKIDAR_USEPOLLING: "true"
       WATCHPACK_POLLING: "true"
       REACT_APP_BACKEND_URL: http://localhost:9001
  backend:
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    ports: 
      - "9001:9001"
    volumes: 
      - ./backend:/app
    networks:
    - INTIA_APP
    environment:
      CHOKIDAR_USEPOLLING: "true"
      PORT: 9001
      DB_URL: mongodb://db:27017/
      DB_NAME: TileDB
      NODE_ENV: development
  admin-client: 
    build:
      context: ./admin-client/
      dockerfile: dev.Dockerfile
    ports: 
        - "3001:3000"
    volumes: 
      - ./admin-client:/app
    networks:
    - INTIA_APP
    environment:
       CHOKIDAR_USEPOLLING: "true"
       WATCHPACK_POLLING: "true"
       REACT_APP_BACKEND_URL: http://localhost:9001
  db:
   image: mongo
   restart: always
   ports:
   - "27017:27017"
   networks:
    - INTIA_APP
   volumes:
    - db-data:/data/db
networks:
  INTIA_APP:
    driver: bridge
volumes:
  db-data:
    driver: local

